apiVersion: v1
kind: Service
metadata:
  name: hello-py-svc
spec:
  selector:
    app: hello-py
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-py
  name: hello-py
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - image: {{image_name}}:{{image_tag}}
        name: hello-py
        ports:
          - containerPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-py-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "{{ingress_host}}"
    http:
      paths:
      - path: /hellopy(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hello-py-svc
            port:
              number: 6000
